
movie_Name = input("Enter movie name: ")
no_of_Sequals = int(input("Enter the number of sequals: "))
no_of_Ticket = int(input("Enter the number of tickets: "))
movie_revenue = float(input("Enter the revenue of movie: "))
no_of_cast = int(input("Enter the number of cast: "))
print("---------------------------------------------")
print("Movie name is: ",movie_Name)
print("Movie has sequeals: ", no_of_Sequals)
print("Number of tickets sold out: ", no_of_Ticket)
print("Movie generated revenue: ", movie_revenue)
print("Movie has number of main cast: ", no_of_cast)
print("----------------------------------------------")
print("Movie name: ",movie_Name ,"Movie Sequeals: ",no_of_Sequals ,"Number of tickets sold out: ",no_of_Ticket ,"Movie generated revenue: ",movie_revenue ,"number of cast in movie: ",no_of_cast)
